type Query {
  # indicatorData is defined in country profiles type file
  getRevenuePerPerson: [IndicatorData]
  getNumberInExtremePoverty: [IndicatorData]
  getPercentageInExtremePoverty: [IndicatorData]
  # we return data for the entire year range
  getBubbleSize(indicatorOrCountry: String): [IndicatorData]
  # IdNamePair is defined in unbundling aid types 
  # this list feeds off oda table from countries and global/concept file
  getIndicatorsList: [IdNamePair]
}

