type BubbleChartData {
  year: Int
  id: String
  name: String
  income_group: String
  region: String
  value: Float
  uid: String
}

type BubbleChartOda {
  year: Int
  # country id
  id: String
  # country name
  name: String
  income_group: String
  region: String
  uid: String
  value: Float
  revenuePerPerson: Float
  numberInExtremePoverty: Float
}

type BubbleChartPoverty {
  year: Int
  value: Float
  id: String
  name: String
  income_group: String
  region: String
  uid: String
  revenuePerPerson: Float
  numberInExtremePoverty: Float
  percentageInExtremePoverty: Float
}
type Region {
  name: String
  id: String
  color: String
}
type BubbleChartOptions {
  # this list feeds off oda table from countries and global/concept file
  # IdNamePair is defined in unbundling aid types 
  indicators: [IdNamePair]
  incomeGroups: [IdNamePair]
  regions: [Region]
}
type Query {
  bubbleChartOda(id: String): [BubbleChartOda]
  bubbleChartPoverty(id: String): [BubbleChartPoverty]
  bubbleChartOptions: BubbleChartOptions
}