language: node_js
node_js:
  - v7
install:
  - yarn --ignore-scripts
  - npm install -g codecov
script:
  - npm run lint
  - npm run build
cache:
  - yarn
  - node_modules

# Allow Travis tests to run in containers.
sudo: false
