language: node_js
node_js:
- v9
before_install:
- npm i -g npm
- npm --version
install:
- npm install
script:
- npm run lint
- npm run build
cache:
  directories:
  - node_modules
sudo: false
notifications:
  slack: devinitorg:TFrmOb61t4X0PRFdZyHBU04F
