// This file is auto generated by the gqlToTs.ts module
// tslint:disable
// graphql typescript definitions

declare namespace DH {
  interface IGraphQLResponseRoot {
    data?: IQuery;
    errors?: Array<IGraphQLResponseError>;
  }

  interface IGraphQLResponseError {
    message: string;            // Required for all errors
    locations?: Array<IGraphQLResponseErrorLocation>;
    [propName: string]: any;    // 7.2.2 says 'GraphQL servers may provide additional entries to error'
  }

  interface IGraphQLResponseErrorLocation {
    line: number;
    column: number;
  }


  interface IQuery {
    bubbleChartOda: Array<IBubbleChartOda> | null;
    bubbleChartPoverty: Array<IBubbleChartPoverty> | null;
    bubbleChartOptions: IBubbleChartOptions | null;
    overviewTab: IOverviewTab | null;
    povertyTab: IPovertyTab | null;
    populationTab: IPopulationTab | null;
    governmentFinance: IGovernmentFinance | null;
    internationalResources: IInternationalResources | null;
    /**
    description: eg recipient or donor
  */
    flows: IFlows | null;
    /**
    description: for area tree map chart dropdown selectoion
  */
    singleResource: ISingleResourceData | null;
    mapData: IMapData | null;
    /**
    description: id is district slug
overviewTabRegional(id: String!, country: String!):OverviewTabRegional
  */
    povertyTabRegional: PovertyTabRegional | null;
    /**
    description: populationTabRegional(id: String!, country: String!):PopulationTabRegional
educationTabRegional(id: String!, country: String!):  EducationTabRegional
healthTabRegional(id: String!, country: String!): HealthTabRegional
  */
    localGovernmentFinance: ILocalGovernmentFinance | null;
    unbundlingAidDataTotal: IUnbundlingAidTotal | null;
    unbundlingAidData: Array<IAidUnit> | null;
    unbundlingSelectionData: IUnbundlingAidSelections | null;
    methodology: Array<IMethodology> | null;
    countries: Array<IEntity> | null;
    districtPageData: Array<IPage> | null;
    countryProfilePageData: Array<IPage> | null;
    odaDonorBubbleChartPageData: Array<IPage> | null;
    globalPicturePageData: Array<IPage> | null;
    povertyBubbleChartPageData: Array<IPage> | null;
    unbundlingOdaPageData: Array<IPage> | null;
    unbundlingOOfPageData: Array<IPage> | null;
    whereThePoorPageData: Array<IPage> | null;
    districts: Array<IDistrict> | null;
    globalPictureThemes: Array<ITheme> | null;
    spotlightThemes: Array<ITheme> | null;
  }


  interface IBubbleChartOda {
    year: number | null;
    /**
    description: country id
  */
    id: string | null;
    /**
    description: country name
  */
    name: string | null;
    income_group: string | null;
    region: string | null;
    uid: string | null;
    value: number | null;
    revenuePerPerson: number | null;
    numberInExtremePoverty: number | null;
  }


  interface IBubbleChartPoverty {
    year: number | null;
    value: number | null;
    id: string | null;
    name: string | null;
    income_group: string | null;
    region: string | null;
    uid: string | null;
    revenuePerPerson: number | null;
    numberInExtremePoverty: number | null;
    percentageInExtremePoverty: number | null;
  }


  interface IBubbleChartOptions {
    /**
    description: this list feeds off oda table from countries and global/concept file
IdNamePair is defined in unbundling aid types 
  */
    indicators: Array<IIdNamePair>;
    incomeGroups: Array<IIdNamePair>;
    regions: Array<IRegion>;
  }


  interface IIdNamePair {
    id: string;
    name: string;
  }


  interface IRegion {
    name: string | null;
    id: string | null;
    color: string | null;
  }


  interface IOverviewTab {
    /**
    description: how many of the poorest people globally live in a country
  */
    poorestPeople: IIndicatorValueWithToolTip | null;
    /**
    description: total population for a given country
  */
    population: IIndicatorValueWithToolTip | null;
    domesticResources: IIndicatorValueWithToolTip | null;
    internationalResources: IIndicatorValueWithToolTip | null;
    /**
    description: recipient countries $PPP, both donor and recipient
  */
    governmentSpendPerPerson: IIndicatorValueWithToolTip | null;
    /**
    description: donor: gross nation income per capit GNI
  */
    averageIncomerPerPerson: IIndicatorDataWithToolTip | null;
    /**
    description: donor: Income share by quintile
  */
    incomeDistTrend: IQuintileDataWithToolTip | null;
  }


  interface IIndicatorValueWithToolTip {
    value: string;
    toolTip: IToolTip;
  }


  interface IToolTip {
    source: string;
    heading: string;
  }


  interface IIndicatorDataWithToolTip {
    data: Array<IIndicatorData>;
    toolTip: IToolTip;
  }


  interface IIndicatorData {
    year: number;
    value: number | null;
    id: string;
    name: string;
    color: string | null;
    uid: string;
  }


  interface IQuintileDataWithToolTip {
    data: Array<IQuintile>;
    toolTip: IToolTip | null;
  }


  interface IQuintile {
    value: number;
    quintileName: string;
    uid: string;
    color: string;
  }


  interface IPovertyTab {
    /**
    description: Poverty reduction over time area chart trend
  */
    poverty190Trend: IIndicatorDataWithToolTip | null;
    /**
    description: how deep is poverty %
  */
    depthOfExtremePoverty: IIndicatorValueWithToolTip | null;
    /**
    description: Recipients: how income is distributed, % of income received by each quintil
  */
    incomeDistTrend: IQuintileDataWithToolTip | null;
  }


  interface IPopulationTab {
    /**
    description: total population in a country
  */
    population: IIndicatorValueWithToolTip | null;
    /**
    description: Urban vs Rural population level
  */
    populationDistribution: IPopulationDistributionWithToolTip | null;
    /**
    description: Number of people in 3 age bands (65+, 15- 65, 0 - 14)
  */
    populationPerAgeBand: IPopulationPerAgeBandWithToolTip | null;
  }


  interface IPopulationDistributionWithToolTip {
    data: Array<IPopulationDistribution>;
    toolTip: IToolTip;
  }


  interface IPopulationDistribution {
    group: string;
    value: number;
    year: number;
  }


  interface IPopulationPerAgeBandWithToolTip {
    data: Array<IPopulationPerAgeBand>;
    toolTip: IToolTip;
  }


  interface IPopulationPerAgeBand {
    band: string;
    value: number;
    year: number;
    uid: string;
  }


  interface IGovernmentFinance {
    startYear: number;
    /**
    description: Total revenue for a particular
  */
    totalRevenue: IIndicatorValueWithToolTip | null;
    grantsAsPcOfRevenue: IIndicatorValueWithToolTip | null;
    /**
    description: for donut chart 
  */
    spendingAllocation: ISpendingAllocationWithToolTip | null;
    /**
    description: for treemap
such as constant 2015 USD for tree map
  */
    currencyCode: string | null;
    currencyUSD: string | null;
    /**
    description: use resourcesRecipient sql
  */
    expenditure: Array<IDomestic> | null;
    revenueAndGrants: Array<IDomestic> | null;
    finance: Array<IDomestic> | null;
  }


  interface ISpendingAllocationWithToolTip {
    data: Array<ISpendingAllocation> | null;
    toolTip: IToolTip;
  }


  interface ISpendingAllocation {
    value: number;
    name: string;
    color: string;
    uid: string;
  }


  interface IDomestic {
    /**
    description: eg Actual or budget
  */
    budget_type: string;
    levels: Array<string>;
    year: number;
    value: number;
    value_ncu: number;
    uid: string;
    color: string;
  }


  interface IInternationalResources {
    startYear: number | null;
    /**
    description: Gross National Income
  */
    GNI: IIndicatorValueWithToolTip | null;
    /**
    description: Net ODA received, % of GNI for recipient countries
  */
    netODAOfGNIIn: IIndicatorValueWithToolTip | null;
    /**
    description: Net ODA out, % of GNI for recipient countries
  */
    netODAOfGNIOut: IIndicatorValueWithToolTip | null;
    /**
    description: for line chart in the  international resources tabs section,
IndicatorDataColoredWithToolTip  is defined in spotlight types
  */
    resourceflowsOverTime: IFlowsOverTimeWithToolTip | null;
    /**
    description: for sidebar chart in international resources section & area partition tree chart default data
  */
    resourcesOverTime: IResourceDataWithToolTip | null;
    /**
    description: Whats the mix of resources can be for donors (out flows) or receipient (in flows)
this is for the donut chart
  */
    mixOfResources: IResourceDataWithToolTip | null;
  }


  interface IFlowsOverTimeWithToolTip {
    data: Array<IIndicatorData>;
    toolTip: IToolTip;
  }


  interface IResourceDataWithToolTip {
    data: Array<IResourceData>;
    toolTip: IToolTip;
  }


  interface IResourceData {
    year: number;
    value: number;
    flow_name: string;
    flow_id: string;
    /**
    description: a position value for a flow generated from flow_type, flow_category and flow name order
  */
    position: number;
    short_name: string;
    /**
    description: Category i.e FDI, ODA
  */
    flow_category: string;
    /**
    description: flow either inflow or outflow
  */
    flow_type: string;
    /**
    description: i.e contains flow type as 1st level, flow category as second and flow name as 3rd
levels: [String]
in or out
  */
    direction: string;
    color: string;
    uid: string;
  }


  interface IFlows {
    /**
    description: an array of inflows for a particular countryType for area & partition chart
  */
    inflows: Array<IFlow>;
    /**
    description: an array of outflows for a particular countryType
  */
    outflows: Array<IFlow>;
  }


  interface IFlow {
    name: string;
    id: string;
    selections: Array<IFlowSelection>;
  }


  interface IFlowSelection {
    name: string;
    /**
    description: this is the group ID
  */
    id: string;
    unbundle: boolean;
  }


  interface ISingleResourceData {
    resources: Array<IIndicatorData>;
    color: string;
  }


  interface IMapData {
    map: Array<IMapUnit>;
    /**
    description: map indicator user friendly label / slug eg Poverty
  */
    name: string;
    /**
    description: map value unit eg US $ or %
  */
    uom_display: string;
    uom: string;
    map_style: string | null;
    source: string;
    start_year: number;
    end_year: number;
    default_year: number;
    description: string | null;
    theme: string;
    heading: string;
    country: string;
    id: string;
    legend: Array<ILegendField>;
  }


  interface IMapUnit {
    /**
    description: country code Id in DW this is di_id
  */
    id: string;
    /**
    description: country slug
  */
    slug: string;
    /**
    description: countryName derived from entity.csv
  */
    name: string;
    year: number;
    color: string | null;
    value: number | null;
    detail: string | null;
    uid: string;
  }


  interface ILegendField {
    label: string;
    color: string;
    backgroundColor: string;
  }


  type PovertyTabRegional = IPovertyTabUg | IPovertyTabKe;




  interface IPovertyTabUg {
    poorestPeople: IIndicatorValueWithToolTip | null;
    /**
    description: WHAT IS THE AVERAGE LIFE EXPECTANCY? 
  */
    lifeExpectancy: IIndicatorValueWithToolTip | null;
    /**
    description: WHAT IS THE STANDARD OF LIVING SCORE? 
  */
    stdOfLiving: IIndicatorValueWithToolTip | null;
  }


  interface IPovertyTabKe {
    poorestPeople: IIndicatorValueWithToolTip | null;
    /**
    description: WHAT IS THE AVERAGE LIFE EXPECTANCY? 
  */
    meanExpenditure: IIndicatorValueWithToolTip | null;
    /**
    description: WHAT IS THE STANDARD OF LIVING SCORE? 
  */
    povertyGap: IIndicatorValueWithToolTip | null;
  }


  interface ILocalGovernmentFinance {
    startYear: number;
    currencyUSD: string;
    currencyCode: string;
    /**
    description: come from finance file
  */
    revenueAndGrants: Array<IDomestic>;
    expenditure: Array<IDomestic>;
  }


  interface IUnbundlingAidToTalQuery {
    /**
    description: oda or oof 
  */
    aidType: string;
    year: number;
  }


  interface IUnbundlingAidTotal {
    year: number;
    total: string;
  }


  interface IUnbundlingAidQuery {
    /**
    description: oda or oof 
  */
    aidType: string;
    year: number;
    /**
    description: eg channel, bundle
  */
    groupBy: string;
    to_di_id?: string | null;
    from_di_id?: string | null;
    /**
    description: form is same as buddle
  */
    bundle?: string | null;
    sector?: string | null;
    channel?: string | null;
  }


  interface IAidUnit {
    /**
    description: this will usually be a summed up aggregate value
  */
    value: number;
    /**
    description: country or organisation or channel or bundle name
  */
    name: string;
    color: string;
    id: string;
    year: number;
    uid: string;
  }


  interface IUnbundlingAidSelections {
    /**
    description: unbundling aid selection options
  */
    to: Array<IIdNamePair>;
    from: Array<IIdNamePair>;
    channels: Array<IIdNamePair>;
    sectors: Array<IIdNamePair>;
    /**
    description: same as form
  */
    bundles: Array<IIdNamePair>;
    years: Array<number>;
  }


  interface IMethodology {
    name: string;
    description: string;
    methodology: string;
    /**
    description: think units
  */
    uom: string;
    source: ISource;
    csv: string;
    zip: string;
  }


  interface ISource {
    name: string;
    link: string;
  }


  interface IEntity {
    id: string;
    name: string;
    slug: string;
    has_domestic_data: string;
    hasPDF: boolean;
    countryType: string;
  }


  interface IPage {
    id: string;
    title: string;
    narrative: string | null;
    donor_title: string | null;
  }


  interface IDistrict {
    id: string;
    name: string;
  }


  interface ITheme {
    id: string;
    name: string;
    default_indicator: string;
    indicators: Array<IThemeIndicator>;
  }


  interface IThemeIndicator {
    heading: string;
    source: string;
    tooltip: string;
    id: string;
    name: string;
  }


  interface IBubbleChartData {
    year: number | null;
    id: string | null;
    name: string | null;
    income_group: string | null;
    region: string | null;
    value: number | null;
    uid: string | null;
  }


  interface IIndicatorValueNCUWithToolTip {
    value: string | null;
    value_ncu: string | null;
    toolTip: IToolTip;
  }


  interface IResourcesBreakDown {
    data: IIndicatorData;
    toolTip: IToolTip;
  }


  interface IOverviewTabRegional {
    /**
    description: WHAT PERCENTAGE OF PEOPLE IN WAKISO LIVE BELOW THE NATIONAL POVERTY LINE? 
can be no data or '12%'
  */
    poorestPeople: IIndicatorValueWithToolTip | null;
    /**
    description: WHAT RESOURCES ARE AVAILABLE TO LOCAL GOVERNMENTS IN WAKISO? eg 3.6m or 2.7bn
this is a total of local, donor and central government resources
  */
    regionalResources: IIndicatorValueNCUWithToolTip | null;
    /**
    description: IndicatorDataColored is defined in country profile types
has local government, donor and central government
  */
    regionalResourcesBreakdown: Array<IResourcesBreakDown> | null;
    /**
    description: HOW MUCH DOES THE LOCAL GOVERNMENT SPEND PER PERSON?
  */
    localGovernmentSpendPerPerson: IIndicatorValueWithToolTip | null;
  }


  interface IPopulationTabRegionalKe {
    /**
    description: The total population of a given district and the population density in per sq km
  */
    totalPopulation: IIndicatorValueWithToolTip | null;
    populationDensity: IIndicatorValueWithToolTip | null;
    populationBirthRate: IIndicatorValueWithToolTip | null;
  }


  interface IPopulationTabRegionalUg {
    /**
    description: The total population of a given district and the population density in per sq km
  */
    totalPopulation: IIndicatorValueWithToolTip | null;
    populationDensity: IIndicatorValueWithToolTip | null;
    /**
    description: Urban vs Rural population level
  */
    populationDistribution: IPopulationDistributionWithToolTip | null;
    averageDependencyRatio: IIndicatorValueWithToolTip | null;
    allAverageDependencyRatio: IIndicatorValueWithToolTip | null;
  }


  interface IEducationTabRegionalUg {
    /**
    description: WHAT IS THE PUPIL–TEACHER RATIO IN PRIMARY EDUCATION?...in government schools  and...in all schools 
  */
    pupilTeacherRatioGovtSchl: IIndicatorValueWithToolTip | null;
    pupilTeacherRatioOtherSchl: IIndicatorValueWithToolTip | null;
    /**
    description: WHAT PERCENTAGE OF STUDENTS PASS THE PRIMARY LEAVING EXAM? 
  */
    studentsPassRate: IIndicatorValueWithToolTip | null;
    studentsPassDistrictRank: IIndicatorValueWithToolTip | null;
    /**
    description: HOW MUCH PRIMARY EDUCATION FUNDING IS THERE? 
  */
    primaryEducationfunding: IIndicatorValueNCUWithToolTip | null;
  }


  interface IEducationTabRegionalKe {
    /**
    description: WHAT IS THE PUPIL–TEACHER RATIO IN PRIMARY EDUCATION?...in government schools  and...in all schools 
  */
    primaryPupilTeacherRatioAllSchl: IIndicatorValueWithToolTip | null;
    primaryTeacherRatioPublicSchl: IIndicatorValueWithToolTip | null;
    primaryTeacherRatioPrivateSchl: IIndicatorValueWithToolTip | null;
  }


  interface IHealthTabRegionalUg {
    /**
    description: WHAT IS THE DISTRICT LEAGUE HEALTH PERFORMANCE SCORE?
  */
    districtPerformance: IIndicatorValueWithToolTip | null;
    /**
    description: WHAT PERCENTAGE OF TUBERCULOSIS CASES HAVE BEEN SUCCESSFULLY TREATED? 
  */
    treatmeantOfTb: IIndicatorValueWithToolTip | null;
    districtHealthRank: IIndicatorValueWithToolTip | null;
    /**
    description: HOW MUCH LOCAL GOVERNMENT HEALTHCARE FUNDING IS THERE? 
  */
    healthCareFunding: IIndicatorValueNCUWithToolTip | null;
  }


  interface IHealthTabRegionalKe {
    birthAttendanceSkilled: IIndicatorValueWithToolTip | null;
    contraceptiveUse: IIndicatorValueWithToolTip | null;
    healthCareFunding: IIndicatorValueNCUWithToolTip | null;
  }
}

// tslint:enable
