
type Download {
  csv: String
  zip: String
}

type DataSources {
  # name of the data you inquiring about
  name: String
  Description: String
  methodology: String
  unit: String
  source: String
  download: Download
}

type Query {
  getMethodologies: [DataSources]
}

