type ThemeIndicator {
  heading: String
  source: String
  id: String
  name: String
}
type Theme {
  id: String
  name: String
  default_indicator: String
  indicators: [ThemeIndicator]
}

type Query {
    globalPictureThemes: [Theme]
    spotlightThemes(country: String!): [Theme]
}