type AidUnit {
  # this will usually be a summed up aggregate value
  value: Float!
  # country or organisation or channel or bundle name
  name: String!
  color: String!
  id: String!
  year: Int!
  uid: String!
}
type IdNamePair {
  id: String!
  name: String!
}
type UnbundlingAidTotal {
  year: Int!
  total: String!
}
type UnbundlingAidSelections {
  # unbundling aid selection options
  to: [IdNamePair]!
  from: [IdNamePair]!   
  channels: [IdNamePair]!
  sectors: [IdNamePair]!
  # same as form
  bundles: [IdNamePair]!
  years: [Int]!
}
input UnbundlingAidToTalQuery {
    # oda or oof 
    aidType: String!
    year: Int!
}
input UnbundlingAidQuery {
    # oda or oof 
    aidType: String!
    year: Int!
    # eg channel, bundle
    groupBy: String!
    to_di_id: String
    from_di_id: String
    bundle: String
    sector: String
    # form is same as buddle
    bundle: String
    channel: String
}

type Query {
  unbundlingAidDataTotal(args: UnbundlingAidToTalQuery): UnbundlingAidTotal
  unbundlingAidData(args: UnbundlingAidQuery):[AidUnit]
  unbundlingSelectionData(aidType: String): UnbundlingAidSelections
}

