type Page {
    id: String!
    title: String!
    narrative: String
    donor_title: String
}
type Query {
  districtPageData(country: String!): [Page]
  countryProfilePageData: [Page]
  odaDonorBubbleChartPageData: [Page]
  globalPicturePageData: [Page]
  povertyBubbleChartPageData: [Page]
  unbundlingOdaPageData: [Page]
  unbundlingOOfPageData: [Page]
  whereThePoorPageData: [Page]
  aboutPageData: [Page]
  footerPageData: [Page]
  frontPageData: [Page]
  spotlightGeneralPageData: [Page]
  unbundlingAidPageData: [Page]
}
