type AidUnit {
  # this will usually be a summed up aggregate value
  value: Float
  # country or organisation or channel or bundle name
  name: String
  color: String
  id: String
  year: Int
  uid: String
}

type IdNamePair {
  id: String
  name: String
}

type UnbundlingAidSelections {
  # unbundling aid selection options
  to: [IdNamePair]
  from: [IdNamePair]
  channels: [IdNamePair]
  sectors: [IdNamePair]
  # same as form
  buddles: [IdNamePair]
  years: [Int]
}

input UnbundlingAidQuery {
    # oda or oof 
    aidType: String!
    year: Int!
    # eg channel, bundle
    groupBy: String!
    to_di_id: String
    from_di_id: String
    sector: String
    # form is same as buddle
    buddle: String
    channel: String
}

type Query {
  unbundlingAidData(args: UnbundlingAidQuery):[AidUnit]
  unbundlingSelectionData(aidType: String): UnbundlingAidSelections
}

