type AidUnit {
  # this will usually be a summed up aggregate value
  value: Float
  # country or organisation or channel or bundle name
  name: String
}
type IdNamePair {
  id: String
  name: String
}

type UnbundlingAidSelections {
  # unbundling aid selection options
  toCountries: [IdNamePair]
  fromCountriesAndOrgs: [IdNamePair]
  channels: [IdNamePair]
  sectors: [IdNamePair]
  form: [IdNamePair]
}

input UnbundlingAidQuery {
    # oda or oof 
    aidType: String!
    years: [Int]!
    # eg channel, bundle
    groupBy: String!
    toCountry: String
    fromCountryOrOrg: String
    sector: String
    form: String
    channel: String
}

type Query {
  getUnbundlingAidData(args: UnbundlingAidQuery):[AidUnit]
  getUnbundlingSelectionData: UnbundlingAidSelections
}

