// This file is auto generated by the gqlToTs.ts module
// tslint:disable
// graphql typescript definitions

declare namespace DH {
  interface IGraphQLResponseRoot {
    data?: IQuery;
    errors?: Array<IGraphQLResponseError>;
  }

  interface IGraphQLResponseError {
    message: string;            // Required for all errors
    locations?: Array<IGraphQLResponseErrorLocation>;
    [propName: string]: any;    // 7.2.2 says 'GraphQL servers may provide additional entries to error'
  }

  interface IGraphQLResponseErrorLocation {
    line: number;
    column: number;
  }

  /*
    description: 
  */
  interface IQuery {
    getCountryProfilePageData: Array<IPage> | null;
    getGlobalPicturePageData: Array<IPage> | null;
    getGlobalPictureThemes: Array<ITheme> | null;
    getGlobalPictureIndicators: Array<IIndicator> | null;
    getOdaDonorBubbleChartPageData: Array<IPage> | null;
    getPovertyBubbleChartPageData: Array<IPage> | null;
    getSpotlightUgandaPageData: Array<IPage> | null;
    getUnbundlingOdaPageData: Array<IPage> | null;
    getUnbundlingOOfPageData: Array<IPage> | null;
    getWhereThePoorPageData: Array<IPage> | null;
    getRevenuePerPersonAndPoverty190: Array<IRevenuePerPersonAndPoverty190> | null;
    getBubbleSize: Array<IBubbleSize> | null;
    getOverViewTab: IOverViewTabRegional | null;
    getPovertyTab: IPovertyTabRegional | null;
    getPopulationTab: IPopulationTabRegional | null;
    getGovernmentFinance: IGovernmentFinance | null;
    getInternationalResources: IInternationalResources | null;
    getSingleResource: ISingleResourceData | null;
    getMapData: IMapData | null;
    getMethodologies: Array<IDataSources> | null;
    getEducationTab: IEducationTabRegional | null;
    getHealthTab: IHealthTabRegional | null;
    getLocalGovernmentFinance: ILocalGovernmentFinance | null;
    getUnbundlingAidData: Array<IAidUnit> | null;
    getUnbundlingSelectionData: IUnbundlingAidSelections | null;
  }

  /*
    description: 
  */
  interface IPage {
    id: string | null;
    title: string | null;
    narrative: string | null;
  }

  /*
    description: 
  */
  interface ITheme {
    id: string | null;
    name: string | null;
    default: string | null;
    order: number | null;
  }

  /*
    description: 
  */
  interface IIndicator {
    id: string | null;
    name: string | null;
    order: number | null;
  }

  /*
    description: 
  */
  interface IRevenuePerPersonAndPoverty190 {
    id: string | null;
    year: number | null;
    poverty: number | null;
    revenuePerPerson: number | null;
  }

  /*
    description: 
  */
  interface IBubbleSize {
    id: string | null;
    year: number | null;
    value: number | null;
  }

  /*
    description: 
  */
  interface IOverViewTabRegional {
    poorestPeople: string | null;
    regionalResources: string | null;
    regionalResourcesBreakdown: Array<IIndicatorDataColored> | null;
    localGovernmentSpendPerPerson: string | null;
  }

  /*
    description: 
  */
  interface IIndicatorDataColored {
    year: number | null;
    Value: number | null;
    id: string | null;
    name: string | null;
    color: string | null;
  }

  /*
    description: 
  */
  interface IPovertyTabRegional {
    poorestPeople: string | null;
    lifeExpectancy: string | null;
    stdOfLiving: string | null;
  }

  /*
    description: 
  */
  interface IPopulationTabRegional {
    totalPopulation: string | null;
    populationDensity: string | null;
    populationDistribution: Array<IPopulationDistribution> | null;
    averageDependencyRatio: string | null;
    allAverageDependencyRatio: string | null;
  }

  /*
    description: 
  */
  interface IPopulationDistribution {
    group: string | null;
    value: number | null;
    year: number | null;
  }

  /*
    description: 
  */
  interface IGovernmentFinance {
    totalRevenue: string | null;
    totalGrants: number | null;
    spendingAllocation: Array<IIndicatorDataColored> | null;
    currencyCode: string | null;
    revenueAndGrants: Array<IDomestic> | null;
    expenditure: Array<IDomestic> | null;
    financing: Array<IDomestic> | null;
  }

  /*
    description: 
  */
  interface IDomestic {
    name: string | null;
    levels: Array<string> | null;
    budgetType: string | null;
    year: number | null;
    value: number | null;
    valueNcu: number | null;
  }

  /*
    description: 
  */
  interface IInternationalResources {
    GNI: string | null;
    netODAOfGNIIn: number | null;
    netODAOfGNIOut: number | null;
    resourcesOverTime: Array<IResourceData> | null;
    mixOfResources: Array<IIndicatorData> | null;
    inflows: Array<IFlow> | null;
    outflows: Array<IFlow> | null;
  }

  /*
    description: 
  */
  interface IResourceData {
    year: number;
    value: number;
    name: string;
    flowCategory: string | null;
    flowType: string | null;
    direction: string | null;
    percentage: number | null;
    color: string | null;
  }

  /*
    description: 
  */
  interface IIndicatorData {
    year: number | null;
    Value: number | null;
    id: string | null;
    name: string | null;
  }

  /*
    description: 
  */
  interface IFlow {
    name: string | null;
    id: string | null;
    selections: Array<IFlowSelection> | null;
  }

  /*
    description: 
  */
  interface IFlowSelection {
    name: string | null;
    id: string | null;
  }

  /*
    description: 
  */
  interface ISingleResourceData {
    resources: Array<IResourceData> | null;
    total: string | null;
  }

  /*
    description: 
  */
  interface IMapData {
    map: Array<IMapUnit> | null;
    name: string | null;
    uomDisplay: string | null;
    uom: string | null;
    startYear: number | null;
    endYear: number | null;
    description: string | null;
    theme: string | null;
    color: string | null;
    total: number | null;
  }

  /*
    description: 
  */
  interface IMapUnit {
    id: string | null;
    countryName: string | null;
    year: number | null;
    value: number | null;
  }

  /*
    description: 
  */
  interface IDataSources {
    name: string | null;
    Description: string | null;
    methodology: string | null;
    unit: string | null;
    source: string | null;
    download: IDownload | null;
  }

  /*
    description: 
  */
  interface IDownload {
    csv: string | null;
    zip: string | null;
  }

  /*
    description: 
  */
  interface IEducationTabRegional {
    pupilTeacherRatioGovtSchl: string | null;
    pupilTeacherRatioOtherSchl: string | null;
    studentsPass: string | null;
    primaryEducationfunding: string | null;
  }

  /*
    description: 
  */
  interface IHealthTabRegional {
    districtPerformance: string | null;
    treatmeantOfTb: string | null;
    healthCareFunding: string | null;
  }

  /*
    description: 
  */
  interface ILocalGovernmentFinance {
    revenue: Array<IDomestic> | null;
    expenditure: Array<IDomestic> | null;
  }

  /*
    description: 
  */
  interface IUnbundlingAidQuery {
    aidType: string;
    year: number;
    groupBy: string;
    toCountry?: string | null;
    fromCountryOrOrg?: string | null;
    sector?: string | null;
    form?: string | null;
    channel?: string | null;
  }

  /*
    description: 
  */
  interface IAidUnit {
    value: number | null;
    name: string | null;
    color: string | null;
  }

  /*
    description: 
  */
  interface IUnbundlingAidSelections {
    toCountries: Array<IIdNamePair> | null;
    fromCountriesAndOrgs: Array<IIdNamePair> | null;
    channels: Array<IIdNamePair> | null;
    sectors: Array<IIdNamePair> | null;
    form: Array<IIdNamePair> | null;
  }

  /*
    description: 
  */
  interface IIdNamePair {
    id: string | null;
    name: string | null;
  }

  /*
    description: 
  */
  interface IGovtRevenuePerPerson {
    id: string | null;
    year: number | null;
    value: number | null;
    type: string | null;
  }

  /*
    description: 
  */
  interface IPoverty190 {
    id: string | null;
    year: number | null;
    value: number | null;
  }

  /*
    description: 
  */
  interface IQuintile {
    value: number | null;
    quintileName: string | null;
  }

  /*
    description: 
  */
  interface IOverViewTabRecipients {
    poorestPeople: string | null;
    population: string | null;
    domesticPublicResources: string | null;
    internationalResources: string | null;
    governmentSpendPerPerson: string | null;
  }

  /*
    description: 
  */
  interface IOverViewTabDonors {
    governmentSpendPerPerson: string | null;
    averageIncomerPerPerson: Array<IIndicatorData> | null;
    incomeDistTrend: Array<IQuintile> | null;
  }

  /*
    description: 
  */
  type OverViewTab = IOverViewTabRecipients | IOverViewTabDonors;



  /*
    description: 
  */
  interface IPovertyTab {
    poverty190Trend: Array<IIndicatorData> | null;
    depthOfExtremePoverty: number | null;
    incomeDistTrend: Array<IQuintile> | null;
  }

  /*
    description: 
  */
  interface IPopulationPerAgeBand {
    band: string | null;
    value: number | null;
    year: number | null;
  }

  /*
    description: 
  */
  interface IPopulationTab {
    population: string | null;
    populationDistribution: Array<IPopulationDistribution> | null;
    populationPerAgeBand: Array<IPopulationPerAgeBand> | null;
  }
}

// tslint:enable
