type Theme {
  id: String
  name: String
  default: String
  order: Int
}

type Indicator {
  id: String
  name: String
  order: Int
}

type Query {
  getGlobalPicturePageData: [Page]
  getGlobalPictureThemes: [Theme]
  getGlobalPictureIndicators(theme: String!): [Indicator]
}
