
type IndicatorDataColored {
  year: Int
  value: Float
  id: String
  name: String
  color: String
  uid: String
}
type  IndicatorDataColoredWithToolTip {
  data: IndicatorDataColored
  toolTip: ToolTip
}
type OverviewTabRegional {
  # WHAT PERCENTAGE OF PEOPLE IN WAKISO LIVE BELOW THE NATIONAL POVERTY LINE? 
  # can be no data or '12%'
  poorestPeople: IndicatorValueWithToolTip
  # WHAT RESOURCES ARE AVAILABLE TO LOCAL GOVERNMENTS IN WAKISO? eg 3.6m or 2.7bn
  # this is a total of local, donor and central government resources
  regionalResources: IndicatorValueWithToolTip
  # IndicatorDataColored is defined in country profile types
  # has local government, donor and central government
  regionalResourcesBreakdown: [IndicatorDataColoredWithToolTip]
  # HOW MUCH DOES THE LOCAL GOVERNMENT SPEND PER PERSON?
  localGovernmentSpendPerPerson: IndicatorValueWithToolTip
}

type PovertyTabRegional {
  poorestPeople: IndicatorValueWithToolTip
  #WHAT IS THE AVERAGE LIFE EXPECTANCY? 
  lifeExpectancy: IndicatorValueWithToolTip
  #WHAT IS THE STANDARD OF LIVING SCORE? 
  stdOfLiving: IndicatorValueWithToolTip
}

type PopulationTabRegional {
  #The total population of a given district and the population density in per sq km
  totalPopulation: IndicatorValueWithToolTip
  populationDensity: IndicatorValueWithToolTip
   # Urban vs Rural population level
  populationDistribution: PopulationDistributionWithToolTip
  averageDependencyRatio: IndicatorValueWithToolTip
  allAverageDependencyRatio: IndicatorValueWithToolTip
}

type EducationTabRegional {
  #WHAT IS THE PUPIL–TEACHER RATIO IN PRIMARY EDUCATION?...in government schools  and...in all schools 
  pupilTeacherRatioGovtSchl: IndicatorValueWithToolTip
  pupilTeacherRatioOtherSchl: IndicatorValueWithToolTip
  #WHAT PERCENTAGE OF STUDENTS PASS THE PRIMARY LEAVING EXAM? 
  studentsPassRate: IndicatorValueWithToolTip
  studentsPassDistrictRank: IndicatorValueWithToolTip
  #HOW MUCH PRIMARY EDUCATION FUNDING IS THERE? 
  primaryEducationfunding: IndicatorValueWithToolTip
}

type HealthTabRegional {
  #WHAT IS THE DISTRICT LEAGUE HEALTH PERFORMANCE SCORE?
  districtPerformance: IndicatorValueWithToolTip
  #WHAT PERCENTAGE OF TUBERCULOSIS CASES HAVE BEEN SUCCESSFULLY TREATED? 
  treatmeantOfTb: IndicatorValueWithToolTip
  districtHealthRank: IndicatorValueWithToolTip
  #HOW MUCH LOCAL GOVERNMENT HEALTHCARE FUNDING IS THERE? 
  healthCareFunding: IndicatorValueWithToolTip
}


type LocalGovernmentFinance {
  startYear: Int
  currencyCode: String
  # come from finance file
  revenueAndGrants: [Domestic]
  expenditure: [Domestic]
}

type Query {  
  # id is district slug
  overviewTabRegional(id: String!, country: String!):OverviewTabRegional
  povertyTabRegional(id: String!, country: String!): PovertyTabRegional
  populationTabRegional(id: String!, country: String!):PopulationTabRegional
  educationTabRegional(id: String!, country: String!): EducationTabRegional
  healthTabRegional(id: String!, country: String!): HealthTabRegional 
  localGovernmentFinance(id: String!, country: String!): LocalGovernmentFinance
}
