type OverViewTabRegional {
  # WHAT PERCENTAGE OF PEOPLE IN WAKISO LIVE BELOW THE NATIONAL POVERTY LINE? 
  # can be no data or '12%
  poorestPeople: String
  # WHAT RESOURCES ARE AVAILABLE TO LOCAL GOVERNMENTS IN WAKISO?
  regionalResources: String
  regionalResourcesBreakdown: [IndicatorDataColored]
  # HOW MUCH DOES THE LOCAL GOVERNMENT SPEND PER PERSON?
  localGovernmentSpendPerPerson: String
}

type Query {  
  getOverViewTab(id: String!):OverViewTabRegional
}

