
type MapUnit {
  # country code Id in DW this is di_id
  id: String
  # countryName derived from entity.csv
  countryName: String
  year: Int
  value: Float
}

type AggregatedMap {
  map: [MapUnit]
  # map indicator user friendly label / slug eg Poverty
  name: String
  # map value unit eg US $ or %
  uomDisplay: String
  uom: String
  startYear: Int
  endYear: Int 
  description: String
  theme: String
  color: String
  # map indicators total for % computations where needed
  total: Float 
}

type Query {
  getMapData(
    id: String!,
    DACOnly: Boolean
  ): AggregatedMap
}