
type MapUnit {
  # country code Id in DW this is di_id
  id: String
  # countryName derived from entity.csv
  countryName: String
  year: Int
  value: Float
}

type AggregatedMap {
  map: [MapUnit]
  # map indeicator user friendly label / slug eg Poverty
  label: String
  # map value unit eg US $ or %
  unit: String
  # map indicators total for % computations where needed
  total: Float 
}

type Query {
  getMapData(
    indicatorType: String!,
    DACOnly: Boolean
  ): AggregatedMap
}