
type MapUnit {
  # country code Id or distict code for case of spotlight uganda
  id: String
  year: Int
  value: Int
}

type AggregatedMap {
  map: [MapUnit]
  # map indeicator user friendly label / slug eg Poverty
  label: String
  # map value unit eg US $ or %
  unit: String
  # map indicators total for % computations where needed
  total: Int 
}

type Query {
  getMapData(
    indicatorType: String!,
    startYear: Int,
    endYear: Int
  ): AggregatedMap
  getDACCountries: [String]
}

