
type LevelData {
  # extreme poverty count 
  poverty: Int 
  # can be worst case, baseline or bestcase
  scenario: String
  year: Int
  # _typeName can be global or regional
  __typeName: String
}

type WhereThePoorWillbe {
  global: [LevelData]
  regional: [LevelData]
}

type Query {
  getWhereThePoorWillbeData: WhereThePoorWillbe
}

