type Page {
    id: String
    title: String
    narrative: String
}
type Query {
  districtPageData: [Page]
  countryProfilePageData: [Page]
  odaDonorBubbleChartPageData: [Page]
  globalPicturePageData: [Page]
  povertyBubbleChartPageData: [Page]
  unbundlingOdaPageData: [Page]
  unbundlingOOfPageData: [Page]
  whereThePoorPageData: [Page]
}